nbafantasy: 
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST_PROD')}}"
      user: "{{ env_var('DB_USER_PROD')}}"
      password: "{{ env_var('DB_PASS_PROD')}}"
      port: 5432       
      dbname: "{{ env_var('DB_NAME_PROD')}}"
      schema: "{{ env_var('DB_SCHEMA_PROD')}}"
      threads: 1
      keepalives_idle: 0    
      connect_timeout: 10    
      retries: 1           